import "./globals.css";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header style={{ margin: "20px 0" }}>THIS IS MY HEADER</header>
        {children}
        <footer style={{ margin: "20px 0" }}>THIS IS MY FOOTER</footer>
      </body>
    </html>
  );
}
